[colors.primary]
background = "#1E1E1E"
foreground = "#D4D4D4"

[font]
size = 12

[font.bold]
family = "InconsolataGo Nerd Font"
style = "Bold"

[font.bold_italic]
family = "InconsolataGo Nerd Font"
style = "Bold Italic"

[font.italic]
family = "InconsolataGo Nerd Font"
style = "Italic"

[font.normal]
family = "InconsolataGo Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 8
y = 8

# [[keyboard.bindings]]
# key = "Return"
# mods = "Shift"
# chars = "\u001b\r"
